### ISSUE TITLE
Ошибка при попытке использования LongPoll

### ISSUE THREAD

**Issue by aquaminer** [getjump/VkApiPHP#24]
Здравствуйте решил попробовать LongPoll в вашей библиотеке, обзавелся кодом с описания выглядит так:
```
use getjump\Vk\Core;
use getjump\Vk\Wrapper\LongPoll;
$vk = Core::getInstance()->apiVersion('5.5')->setToken('token');
         $lp = new LongPoll($vk);
         $lp->doLoop();
```
При исполнении кода когда проходит 30 сек. получаю это: 
```
Exception: cURL error 7: Failed to connect to imv4.vk.com port 80: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in [ /vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php, line 186]
2017-05-06 16:30:20 Error: [GuzzleHttp\Exception\ConnectException] cURL error 7: Failed to connect to imv4.vk.com port 80: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in  /vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 186
Stack Trace:
#0  /vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1  /vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2  /vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3  /vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4  /vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5  /vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(42): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6  /vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7  /vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(68): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8  /vendor/guzzlehttp/guzzle/src/Middleware.php(59): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9  /vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#10  /vendor/guzzlehttp/guzzle/src/Client.php(275): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#11  /vendor/guzzlehttp/guzzle/src/Client.php(123): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#12  /vendor/guzzlehttp/guzzle/src/Client.php(129): GuzzleHttp\Client->requestAsync('get', 'http://imv4.vk....', Array)
#13  /vendor/guzzlehttp/guzzle/src/Client.php(87): GuzzleHttp\Client->request('get', 'http://imv4.vk....', Array)
#14  /vendor/getjump/vk/src/getjump/Vk/Wrapper/LongPoll.php(70): GuzzleHttp\Client->__call('get', Array)
#15  /vendor/getjump/vk/src/getjump/Vk/Wrapper/LongPoll.php(70): GuzzleHttp\Client->get('http://imv4.vk....')
#16  /src/Shell/FriendsShell.php(53): getjump\Vk\Wrapper\LongPoll->doLoop()

```

**Comment by wislert** [comment]
+1

**Comment by aquaminer** [comment]
Если кого то тоже интересует как реализовать long poll рекомендую использовать эту [либу](https://github.com/AlexBrin/VKPageBot)
