### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by Andreslav** [getjump/VkApiPHP#30]
Здравствуйте!
```
yii\base\ErrorException: Invalid argument supplied for foreach() in /var/www/u46770/data/www/vendor/getjump/vk/src/getjump/Vk/Response/Response.php:41 Stack trace: #0 /var/www/u46770/data/www/vendor/getjump/vk/src/getjump/Vk/Response/Response.php(41): yii\base\ErrorHandler->handleError(2, 'Invalid argumen...', '/var/www/u46770...', 41, Array) #1 /var/www/u46770/data/www/vendor/getjump/vk/src/getjump/Vk/Response/Api.php(25): getjump\Vk\Response\Response->__construct(1, false)
...
```

VK Возвращает ответ вида:
```
{
"response": 1
}
```

Полагаю, __construct() пытается обработать его, как массив. 
```
public function __construct($data, $callback = false)
    {
        foreach ($data as $key => $value) {
            if (property_exists($this, $key)) {
                continue;
            }

            $this->{$key} = $value;
            $this->extendedFields[] = $key;
        }
...
```

Что порекомендуете?

**Comment by seryozhasa** [comment]
Та же ситуация, почему то от вк иногда не массив приходит

**Comment by Andreslav** [comment]
> 
> 
> Та же ситуация, почему то от вк иногда не массив приходит

Всё по документации, вк не всегда возвращает массив, что автор видимо не учёл.

Я решил проблему по-своему:
```
if (is_array($data)) {
    foreach ($data as $key => $value) {
        if (property_exists($this, $key)) {
            continue;
        }

        $this->{$key} = $value;
        $this->extendedFields[] = $key;
    }
} else {
    $this->val = $data;
}
```
